# Generated by Django 6.0.5 on 2026-05-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('numero_tel', models.CharField(max_length=20)),
                ('motdepasse', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilisateur.utilisateur')),
            ],
            bases=('Utilisateur.utilisateur',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilisateur.utilisateur')),
                ('adresse', models.CharField(max_length=255)),
            ],
            bases=('Utilisateur.utilisateur',),
        ),
    ]
