# Generated by Django 6.0.5 on 2026-05-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produits', '__first__'),
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('RETOURNEE', 'Retournée')], default='EN_ATTENTE', max_length=30)),
                ('total', models.FloatField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_gerees', to='Utilisateur.admin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Utilisateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('idLigne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('prixUnitaire', models.FloatField()),
                ('sousTotal', models.FloatField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='Produits.produit')),
            ],
        ),
    ]
