# Generated by Django 6.0.5 on 2026-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='reduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_apres_reduction',
            field=models.FloatField(default=0),
        ),
    ]
