# Generated by Django 6.0.5 on 2026-05-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idProduit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('stock', models.IntegerField(default=0)),
                ('dateAjout', models.DateField(auto_now_add=True)),
                ('dateModif', models.DateField(auto_now=True)),
                ('dateSupp', models.DateField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_geres', to='Utilisateur.admin')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Produits.categorie')),
            ],
        ),
    ]
