# Generated by Django 6.0.5 on 2026-05-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_promotion_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='clients',
        ),
    ]
